dockerized_dbt:
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      threads: 1
      type: snowflake
  target: dev